CREATE DATABASE studyYourself;

CREATE TABLE users( 
	id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, 
	username VARCHAR(50) NOT NULL, 
	password VARCHAR(255) NOT NULL, 
	completeName VARCHAR(55) NOT NULL, 
	email VARCHAR(50) NOT NULL, 
	role VARCHAR(20) NOT NULL, 
	created DATETIME DEFAULT NULL, 
	modified DATETIME DEFAULT NULL 
);

CREATE TABLE materials(
	id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	title VARCHAR(200) NOT NULL,
	created DATETIME DEFAULT NULL,
	modified DATETIME DEFAULT NULL, 
	user_id INT NOT NULL,
	category_id INT NOT NULL
);

CREATE TABLE pages(
	id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	data TEXT NOT NULL,
	material_id INT NOT NULL
);

CREATE TABLE categories(
	id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(100) NOT NULL,
	parent_id INTEGER DEFAULT NULL,
	lft INTEGER(10),
	rght INTEGER(10),
	created DATETIME DEFAULT NULL,
	modified DATETIME DEFAULT NULL
);
